//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TD.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới ứng dụng thành công.
        /// </summary>
        internal static string ProductAdded {
            get {
                return ResourceManager.GetString("ProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin ứng dụng thành công.
        /// </summary>
        internal static string ProductChanged {
            get {
                return ResourceManager.GetString("ProductChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy ứng dụng.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa ứng dụng.
        /// </summary>
        internal static string ProductRemoved {
            get {
                return ResourceManager.GetString("ProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm phiên bản ứng dụng.
        /// </summary>
        internal static string ProductVersionAdded {
            get {
                return ResourceManager.GetString("ProductVersionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật thông tin phiên bản.
        /// </summary>
        internal static string ProductVersionChanged {
            get {
                return ResourceManager.GetString("ProductVersionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại phiên bản ứng dụng này.
        /// </summary>
        internal static string ProductVersionExist {
            get {
                return ResourceManager.GetString("ProductVersionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phiên bản ứng dụng.
        /// </summary>
        internal static string ProductVersionNotFound {
            get {
                return ResourceManager.GetString("ProductVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa phiên bản.
        /// </summary>
        internal static string ProductVersionRemoved {
            get {
                return ResourceManager.GetString("ProductVersionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bài viết thành công.
        /// </summary>
        internal static string BlogChanged {
            get {
                return ResourceManager.GetString("BlogChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bài viết thành công.
        /// </summary>
        internal static string BlogInserted {
            get {
                return ResourceManager.GetString("BlogInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề bài viết này đã được sử dụng.
        /// </summary>
        internal static string BlogNameUsed {
            get {
                return ResourceManager.GetString("BlogNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa bài viết.
        /// </summary>
        internal static string BlogRemoved {
            get {
                return ResourceManager.GetString("BlogRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant remove your phone number.
        /// </summary>
        internal static string CantRemoveYourPhoneNumber {
            get {
                return ResourceManager.GetString("CantRemoveYourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thay đổi email.
        /// </summary>
        internal static string EmailChanged {
            get {
                return ResourceManager.GetString("EmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng.
        /// </summary>
        internal static string EmailUsed {
            get {
                return ResourceManager.GetString("EmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới chức năng ứng dụng thành công.
        /// </summary>
        internal static string FeatureProductProductAdded {
            get {
                return ResourceManager.GetString("FeatureProductProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chức năng ứng dụng thành công.
        /// </summary>
        internal static string FeatureProductProductChanged {
            get {
                return ResourceManager.GetString("FeatureProductProductChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng này đã có sẵn trên ứng dụng.
        /// </summary>
        internal static string FeatureProductProductExist {
            get {
                return ResourceManager.GetString("FeatureProductProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại chức năng này.
        /// </summary>
        internal static string FeatureProductExits {
            get {
                return ResourceManager.GetString("FeatureProductExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already taken!.
        /// </summary>
        internal static string HasAlreadyTaken {
            get {
                return ResourceManager.GetString("HasAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng mở email bạn đã đăng ký : {0} và xác minh tài khoản.
        /// </summary>
        internal static string HelpVerifyAccount {
            get {
                return ResourceManager.GetString("HelpVerifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số này đã có dữ liệu .
        /// </summary>
        internal static string InfoProductExist {
            get {
                return ResourceManager.GetString("InfoProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông số kỹ thuật thành công.
        /// </summary>
        internal static string InfoProductRemoved {
            get {
                return ResourceManager.GetString("InfoProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên đăng nhập hoặc mật khẩu.
        /// </summary>
        internal static string InvalidLoginInfo {
            get {
                return ResourceManager.GetString("InvalidLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật họ tên.
        /// </summary>
        internal static string NameChanged {
            get {
                return ResourceManager.GetString("NameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn khách hàng.
        /// </summary>
        internal static string NeedPartner {
            get {
                return ResourceManager.GetString("NeedPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới khách hàng thành công.
        /// </summary>
        internal static string PartnerProductAdded {
            get {
                return ResourceManager.GetString("PartnerProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật khách hàng thành công.
        /// </summary>
        internal static string PartnerProductChanged {
            get {
                return ResourceManager.GetString("PartnerProductChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng này đã sử dụng ứng dụng.
        /// </summary>
        internal static string PartnerProductExist {
            get {
                return ResourceManager.GetString("PartnerProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng này chưa sử dụng ứng dụng.
        /// </summary>
        internal static string PartnerProductNotFound {
            get {
                return ResourceManager.GetString("PartnerProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerExist.
        /// </summary>
        internal static string PartnerExist {
            get {
                return ResourceManager.GetString("PartnerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác.
        /// </summary>
        internal static string PasswordNotValid {
            get {
                return ResourceManager.GetString("PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your code.
        /// </summary>
        internal static string PleaseCheckYourCode {
            get {
                return ResourceManager.GetString("PleaseCheckYourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid password.
        /// </summary>
        internal static string PleaseEnterValidPassword {
            get {
                return ResourceManager.GetString("PleaseEnterValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã tạo thành công tài khoản tại {0} , để trải nghiệm đầy đủ tính năng của chúng tôi, vui lòng &lt;a href=&quot;{1}&quot;&gt;xác minh tài khoản&lt;/a&gt;.
        /// </summary>
        internal static string PleaseVerifyYourAccount {
            get {
                return ResourceManager.GetString("PleaseVerifyYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin sản phẩm thành công.
        /// </summary>
  
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thông số.
        /// </summary>
        internal static string ProductInfoRequire {
            get {
                return ResourceManager.GetString("ProductInfoRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới sản phẩm thành công.
        /// </summary>
        internal static string ProductInserted {
            get {
                return ResourceManager.GetString("ProductInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm.
        /// </summary>
   
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa sản phẩm thành công.
        /// </summary>

        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng mở email {0} và làm theo hướng dẫn để tạo mới mật khẩu.
        /// </summary>
        internal static string ResetPasswordHelp {
            get {
                return ResourceManager.GetString("ResetPasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string ResetPasswordMail {
            get {
                return ResourceManager.GetString("ResetPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật chữ ký.
        /// </summary>
        internal static string SignChanged {
            get {
                return ResourceManager.GetString("SignChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống SMS đã tắt.
        /// </summary>
        internal static string SMSOff {
            get {
                return ResourceManager.GetString("SMSOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhãn thành công.
        /// </summary>
        internal static string TagBlogChanged {
            get {
                return ResourceManager.GetString("TagBlogChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhãn thành công.
        /// </summary>
        internal static string TagBlogInserted {
            get {
                return ResourceManager.GetString("TagBlogInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhãn thành công.
        /// </summary>
        internal static string TagBlogRemove {
            get {
                return ResourceManager.GetString("TagBlogRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn đã được sử dụng.
        /// </summary>
        internal static string TagBlogUsed {
            get {
                return ResourceManager.GetString("TagBlogUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật thông tin người dùng.
        /// </summary>
        internal static string UserChanged {
            get {
                return ResourceManager.GetString("UserChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserHasCreated.
        /// </summary>
        internal static string UserHasCreated {
            get {
                return ResourceManager.GetString("UserHasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm mới người dùng.
        /// </summary>
        internal static string UserInserted {
            get {
                return ResourceManager.GetString("UserInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã được sử dụng.
        /// </summary>
        internal static string UserNameUsed {
            get {
                return ResourceManager.GetString("UserNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa người dùng.
        /// </summary>
        internal static string UserRemoved {
            get {
                return ResourceManager.GetString("UserRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật chức năng phiên bản.
        /// </summary>
        internal static string VersionFeatureProductChanged {
            get {
                return ResourceManager.GetString("VersionFeatureProductChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa chức năng phiên bản.
        /// </summary>
        internal static string VersionFeatureProductRemoved {
            get {
                return ResourceManager.GetString("VersionFeatureProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been delete!.
        /// </summary>
        internal static string YourAccountHasBeenDelete {
            get {
                return ResourceManager.GetString("YourAccountHasBeenDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account has been lockout.
        /// </summary>
        internal static string YourAccountHasBeenLockout {
            get {
                return ResourceManager.GetString("YourAccountHasBeenLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your avatar has been set!.
        /// </summary>
        internal static string YourAvatarHasBeenSet {
            get {
                return ResourceManager.GetString("YourAvatarHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has been set.
        /// </summary>
        internal static string YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number has been set!.
        /// </summary>
        internal static string YourPhoneNumberHasBeenSet {
            get {
                return ResourceManager.GetString("YourPhoneNumberHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username has been set!.
        /// </summary>
        internal static string YourUsernameHasBeenSet {
            get {
                return ResourceManager.GetString("YourUsernameHasBeenSet", resourceCulture);
            }
        }
    }
}
